name: Export Power Platform Solution

on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: 'Solution Name'
        required: true
        default: 'GPPB'
      solutionPath:
        description: 'Solution Path'
        required: true
        default: 'devops-in-a-day/src/PowerPlatform'
      solutionType:
        description: 'Solution Type'
        required: true
        default: 'Unmanaged'

# ⬆️ 이벤트 트리거 조건을 설정합니다.
env:
  ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}
  APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  DIRECTORY_ID: ${{ secrets.DIRECTORY_ID }}

# ⬆️ 환경 변수를 설정합니다.
permissions:
  contents: write

# ⬆️ GitHub 액션 권한을 설정합니다.
jobs:
  export_solution:
    runs-on: ubuntu-latest

    # ⬆️ 빌드 서버를 설정합니다.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ⬆️ 리포지토리 체크아웃 액션
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # ⬆️ 파워 플랫폼 CLI 설치 액션
      - name: Who am I?
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.APPLICATION_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          tenant-id: ${{ env.DIRECTORY_ID }}

      # ⬆️ 현재 작업할 파워 플랫폼 환경 체크 액션
      - name: Export solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.APPLICATION_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          tenant-id: ${{ env.DIRECTORY_ID }}
          solution-name: ${{ github.event.inputs.solutionName }}
          solution-output-file: ${{ github.event.inputs.solutionPath}}/${{ github.event.inputs.solutionName }}.zip

      # ⬆️ 파워 플랫폼 솔루션 내보내기 액션
      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: ${{ github.event.inputs.solutionPath }}/${{ github.event.inputs.solutionName }}.zip
          solution-folder: ${{ github.event.inputs.solutionPath }}/${{ github.event.inputs.solutionName }}
          solution-type: ${{ github.event.inputs.solutionType }}
          overwrite-files: true

      # ⬆️ 파워 플랫폼 솔루션 압축 풀기 액션
      - name: Branch solution
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: ${{ github.event.inputs.solutionPath}}/${{ github.event.inputs.solutionName }}
          solution-target-folder: ${{ github.event.inputs.solutionPath}}/${{ github.event.inputs.solutionName }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true

      # ⬆️ 파워 플랫폼 솔루션 새 브랜치 커밋/푸시 액션